### PR TITLE
Uploader Update

### PR DESCRIPTION
**Pull request by aelfa**

### CODE REVIEW

**Comment by aelfa** [comment]
Fixed a missing "'"

**Comment by thesammykins** [comment]
Please resolve the following conflicts before we can merge this

>  excluded/transport.exclude
> scripts/cloneclean.sh
> ymls/uploader.yml 

We would advise working this into an alternative to the current uploader to better suit more advanced users as the current uploader is simplistic and easy to use by users whom are not suited to more advanced options.

I'll be closing this pull as it doesn't align with the goals of PTS in being a refined and easy to maintain project as this adds more complexity than it is worth.

**Comment by aelfa** [comment]
Those issues were to resolved at your end, secondly this is not a new uploader it's made on top of PhysK's uploader. The differences being uploads are directly done from the downloads location, clone clean is optimized. Bandwidth can be controlled. Automatic bandwidth throttle whilst a Plex stream is running and Discord Webhooks included. There is however no changes made to core PTS components.

**Comment by aelfa** [comment]
The issues can be resolved by you just by clicking on resolve issues simply.

**Pull request closed without merging**
